[project]
name = "langgraph-tutorials"
version = "0.1.0"
description = "Playing Around with LangGraph"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "colorama>=0.4.6",
    "langchain>=0.3.27",
    "langchain-ollama>=0.3.6",
    "langgraph>=0.6.1",
]
